- .gitignore
- .idea/.gitignore
- .idea/codeStyles/codeStyleConfig.xml
- .idea/compiler.xml
- .idea/encodings.xml
- .idea/git_toolbox_prj.xml
- .idea/jarRepositories.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/springboot-jpa.iml
- .idea/vcs.xml
- kdt.iml
- pom.xml
- src/main/java/org/prgrms/kdt/Application.java
- src/main/java/org/prgrms/kdt/config/DataSourceConfig.java
- src/main/java/org/prgrms/kdt/domain/Customer.java
- src/main/java/org/prgrms/kdt/domain/CustomerRepository.java
- src/main/resources/application.yml
- src/test/java/org/prgrms/kdt/ApplicationTest.java
- src/test/java/org/prgrms/kdt/domain/CustomerRepositoryTest.java
- 고객(Customer) 엔티티는 ID(PK), 이름, 성을 가진다.
- 고객엔티티를 이용한 CRUD를 구현한다.
> [2기-P] 곽동운 Mission 1: JPA 소개

- src/main/java/com/study/springbootJpa/Config/DataSourceConfig.java
- src/main/java/com/study/springbootJpa/domain/Customer.java
- src/main/resources/application.yml
- src/test/java/com/study/springbootJpa/PersistenceContextTest.java
- customer 엔티티를 이용하여 영속성컨텍스트의 엔티티 생명주기를 실습해본다.
> [2기-P] 박혜빈 Mission 2: 영속성컨텍스트 

- jpa2/src/main/java/com/part4/jpa2/domain/Item.java
- jpa2/src/main/java/com/part4/jpa2/domain/Member.java
- jpa2/src/main/java/com/part4/jpa2/domain/Order.java
- jpa2/src/main/java/com/part4/jpa2/domain/OrderItem.java
- jpa2/src/main/java/com/part4/jpa2/domain/OrderStatus.java
- jpa2/src/main/resources/application.yaml
- jpa2/src/test/java/com/part4/jpa2/CustomerRepositoryTest.java
- jpa2/src/test/java/com/part4/jpa2/OrderPersistenceTest.java
- jpa2/src/test/java/com/part4/jpa2/PersistenceContextTest.java
> [2기-P] 김수빈 Mission 2: 영속성컨텍스트

- src/test/java/prgrms/assignment/jpa/repository/PersistenceContextLifecycleTest.java
> [2-P] 김성현 Mission 2: 영속성 컨텍스트

- pom.xml
- src/main/java/org/prgrms/kdt/domain/Customer.java
- src/test/java/org/prgrms/kdt/domain/CustomerPersistenceContextTest.java
> [2기-P] 곽동운 Mission 2: 영속성컨텍스트

- app/build.gradle
- app/src/main/resources/application.yml
- app/src/test/java/com/programmers/app/persistent/ContextTest.java
> [2기-P]김병연 Mission 2: 영속성컨텍스트

- src/test/java/com/example/assignment1/domain/PersistenceContextTest.java
> [2기-P] 정윤오 Mission 2: 영속성 컨텍스트

- src/main/java/com/kdt/jpaproject/domain/Customer.java
- src/test/java/com/kdt/jpaproject/PersistenceContextTest.java
- src/test/java/com/kdt/jpaproject/domain/CustomerRepositoryTest.java
customer 엔티티를 이용하여 영속성컨텍스트의 엔티티 생명주기를 실습해본다.[완]
> [2기-P]  이용훈 Mission 2: 영속성 컨텍스트

- springboot-jpa/.gitignore
- springboot-jpa/README.md
- springboot-jpa/pom.xml
- springboot-jpa/src/main/java/com/example/springjpa/SpringJpaApplication.java
- springboot-jpa/src/main/java/com/example/springjpa/config/DataSourceConfig.java
- springboot-jpa/src/main/java/com/example/springjpa/domain/Customer.java
- springboot-jpa/src/main/java/com/example/springjpa/domain/Item.java
- springboot-jpa/src/main/java/com/example/springjpa/domain/Member.java
- springboot-jpa/src/main/java/com/example/springjpa/domain/Order.java
- springboot-jpa/src/main/java/com/example/springjpa/domain/OrderItem.java
- springboot-jpa/src/main/java/com/example/springjpa/domain/OrderStatus.java
- springboot-jpa/src/main/java/com/example/springjpa/inherit/Car.java
- springboot-jpa/src/main/java/com/example/springjpa/inherit/Food.java
- springboot-jpa/src/main/java/com/example/springjpa/inherit/Furniture.java
- springboot-jpa/src/main/java/com/example/springjpa/inherit/ParentItem.java
- springboot-jpa/src/main/java/com/example/springjpa/repository/CustomerRepository.java
- springboot-jpa/src/main/resources/application.yaml
- springboot-jpa/src/test/java/com/example/springjpa/inherit/InheritTest.java
- springboot-jpa/src/test/java/com/example/springjpa/repository/CustomerRepositoryTest.java
- springboot-jpa/src/test/java/com/example/springjpa/repository/EntityManagerTest.java
- springboot-jpa/src/test/java/com/example/springjpa/repository/RelationTest.java
- Customer entity 생성
- CustomerRepository의 CRUD와 test추가
> [2기-C 길근오] CustomerRepository 생성 & CRUD 테스트

- src/main/java/com/kdt/lecture/domain/Customer.java
- src/main/resources/application.yml
- src/test/java/com/kdt/lecture/domain/PersistTest.java
> [2기-P] 김형욱 Mission 2: 영속성컨텍스트

- src/main/resources/application.yaml
- src/test/java/com/prgrms/springJpa/domain/PersistenceContextTest.java
> [2기-P] 유민환 Mission 2: 영속성컨텍스트

- src/test/java/com/prgms/mission_jpa/customer/CustomerPersistenceContextTest.java
> [2기-P] 강용수 Mission 2: 영속성컨텍스트

- demo/src/main/java/com/example/demo/domain/Customer.java
- demo/src/main/java/com/example/demo/repository/CustomerRepository.java
- demo/src/main/resources/application.yaml
- demo/src/test/java/com/example/demo/persistence/CustomerPersistenceTest.java
- demo/src/test/java/com/example/demo/repository/CustomerRepositoryTest.java
혹시 봐주신다면 [feat : Customer 엔티티를 이용한 CRUD를 구현한다](https://github.com/prgrms-be-devcourse/springboot-jpa/commit/aad1a354144dbda3a6d30a8313a1e211340527c2)
이 커밋만 봐주시면 될것같습니다 ! 
다른것들은 1차 미션 리펙토링한것입니다..!
> [2기-P] 이예림 Mission 2: 영속성 컨텍스트

- src/main/java/com/example/kdtjpa/domain/BaseEntity.java
- src/main/java/com/example/kdtjpa/domain/customer/Customer.java
- src/main/java/com/example/kdtjpa/domain/customer/CustomerRepository.java
- src/main/java/com/example/kdtjpa/domain/item/Car.java
- src/main/java/com/example/kdtjpa/domain/item/Food.java
- src/main/java/com/example/kdtjpa/domain/item/Furniture.java
- src/main/java/com/example/kdtjpa/domain/item/Item.java
- src/main/java/com/example/kdtjpa/domain/member/Member.java
- src/main/java/com/example/kdtjpa/domain/order/Order.java
- src/main/java/com/example/kdtjpa/domain/order/OrderStatus.java
- src/main/java/com/example/kdtjpa/domain/orderItem/OrderItem.java
- src/test/java/com/example/kdtjpa/domain/customer/CustomerRepositoryTest.java
* customer 패키지 생성
* order, orderItem 연관관계
* order(1) : orderItem(n)으로 양방향 연관관계를 설정하였습니다.  
* orderItem은 order엔티티에 종속된 엔티티라고 생각하여 casecade.all & orphanRemoval = true로 설정하였습니다.
* orderItem, item 연관관계 
* item(1) : orderItem(n)으로 item -> orderItem은 연관관계가 필요 없을듯하여 단방향 연관관계로 설정하였습니다.
* order, member 연관관계
* member(1) : order(n)으로 member -> order는 연관관계가 필요 없을듯하여 단방향 연관관계로 설정하였습니다.
> [2기-C] 정하영 -  Mission 3: 연관관계 매핑

- .gitignore
- mvnw
- mvnw.cmd
- pom.xml
- src/main/java/com/example/jpademo/JpaDemoApplication.java
- src/main/java/com/example/jpademo/config/DataSourceConfig.java
- src/main/java/com/example/jpademo/domain/Customer.java
- src/main/java/com/example/jpademo/domain/CustomerRepository.java
- src/main/resources/application.yml
- src/test/java/com/example/jpademo/JpaDemoApplicationTests.java
- src/test/java/com/example/jpademo/domain/CustomerRepositoryTest.java
- Jpa를 이용한 crud 만들기
- jpa 형태로 레포지토리를 구현해 두고, 해당 레포지토리에 대한 테스트 코드를 작성했습니다.
> [2기-P] 김진욱 springboot-jpa mission 1입니다.

- src/main/java/com/kdt/springbootjpa/common/entity/BaseEntity.java
- src/main/java/com/kdt/springbootjpa/item/domain/Car.java
- src/main/java/com/kdt/springbootjpa/item/domain/Food.java
- src/main/java/com/kdt/springbootjpa/item/domain/Furniture.java
- src/main/java/com/kdt/springbootjpa/item/domain/Item.java
- src/main/java/com/kdt/springbootjpa/member/domain/Member.java
- src/main/java/com/kdt/springbootjpa/order/domain/Order.java
- src/main/java/com/kdt/springbootjpa/order/domain/OrderItem.java
- src/main/java/com/kdt/springbootjpa/order/domain/OrderStatus.java
> [2기-C] 김산 - :sparkles: Mission 3: 연관관계 매핑

- .gitignore
- mvnw
- mvnw.cmd
- pom.xml
- src/main/java/com/example/jpademo/JpaDemoApplication.java
- src/main/java/com/example/jpademo/config/DataSourceConfig.java
- src/main/java/com/example/jpademo/domain/Customer.java
- src/main/java/com/example/jpademo/domain/CustomerRepository.java
- src/main/resources/application.yml
- src/test/java/com/example/jpademo/JpaDemoApplicationTests.java
- src/test/java/com/example/jpademo/domain/CustomerRepositoryTest.java
- src/test/java/com/example/jpademo/domain/PersistenceContextTest.java
- 영속성 컨텍스트를 이용한 데이터 crud
- 테스트 코드를 통한 영속성 컨텍스트 기능 검증
- 커밋 이전과 이후를 구분하여 테스트 코드 작성
- mission1과 비교하여 PersistenceContextTest.java만 변경되었습니다. 해당 부분만 확인하시면 될 듯 합니다.
> [2기-P] 김진욱 Mission2 영속성 컨텍스트

- lec_JPA/build.gradle
- lec_JPA/src/main/java/com/prgrms/lec_jpa/domain/BaseEntity.java
- lec_JPA/src/main/java/com/prgrms/lec_jpa/domain/Item.java
- lec_JPA/src/main/java/com/prgrms/lec_jpa/domain/Member.java
- lec_JPA/src/main/java/com/prgrms/lec_jpa/domain/Order.java
- lec_JPA/src/main/java/com/prgrms/lec_jpa/domain/OrderItem.java
- lec_JPA/src/test/java/com/prgrms/lec_jpa/domain/CustomerRepositoryTest.java
- lec_JPA/src/test/java/com/prgrms/lec_jpa/domain/OrderPersistentTest.java
롬복 사용을 지양하고자 롬복 의존성을 제거하고 기본 생성자와 테스트에서 사용하는 Logger를 추가했습니다!
> [2기 -C] 유재희 :fire: delete :  롬복 의존성 제거

- build.gradle
- src/main/java/com/kdt/JpaWeekly/common/domain/BaseEntity.java
- src/main/java/com/kdt/JpaWeekly/domain/item/Car.java
- src/main/java/com/kdt/JpaWeekly/domain/item/Food.java
- src/main/java/com/kdt/JpaWeekly/domain/item/Furniture.java
- src/main/java/com/kdt/JpaWeekly/domain/item/Item.java
- src/main/java/com/kdt/JpaWeekly/domain/member/Member.java
- src/main/java/com/kdt/JpaWeekly/domain/order/Order.java
- src/main/java/com/kdt/JpaWeekly/domain/order/OrderItem.java
- src/main/java/com/kdt/JpaWeekly/domain/order/OrderStatus.java
빌더 패턴을 적용하여 엔티티를 생성하고 연관관계 매핑하였습니다.
> [2기-C]류영준 - 연관관계 매핑

- build.gradle
- src/main/java/com/kdt/springbootjpa/common/entity/BaseEntity.java
- src/main/java/com/kdt/springbootjpa/item/domain/Car.java
- src/main/java/com/kdt/springbootjpa/item/domain/Food.java
- src/main/java/com/kdt/springbootjpa/item/domain/Furniture.java
- src/main/java/com/kdt/springbootjpa/item/domain/Item.java
- src/main/java/com/kdt/springbootjpa/member/domain/Member.java
- src/main/java/com/kdt/springbootjpa/order/domain/Order.java
- src/main/java/com/kdt/springbootjpa/order/domain/OrderItem.java
롬복을 제거하고, 다음 pr에서는 base entity 에 audit 기능을 적용하려 합니다
> [2기-C] 김산 - JPA Mission 3 롬복 제거

- pom.xml
- src/main/java/com/example/kdtjpa/domain/BaseEntity.java
- src/main/java/com/example/kdtjpa/domain/customer/Customer.java
- src/main/java/com/example/kdtjpa/domain/item/Car.java
- src/main/java/com/example/kdtjpa/domain/item/Food.java
- src/main/java/com/example/kdtjpa/domain/item/Furniture.java
- src/main/java/com/example/kdtjpa/domain/item/Item.java
- src/main/java/com/example/kdtjpa/domain/member/Member.java
- src/main/java/com/example/kdtjpa/domain/order/Order.java
- src/main/java/com/example/kdtjpa/domain/orderItem/OrderItem.java
- src/test/java/com/example/kdtjpa/domain/customer/CustomerRepositoryTest.java
최대한 롬복 사용을 지양하고자 기존 코드에서 롬복 의존성을 제거하였습니다!
> [2기-C] 정하영 - JPA Mission 3 롬복 의존성 제거

- src/main/java/com/kdt/springbootjpa/SpringbootJpaApplication.java
- src/main/java/com/kdt/springbootjpa/common/entity/AccountAuditAware.java
- src/main/java/com/kdt/springbootjpa/common/entity/BaseEntity.java
- src/main/java/com/kdt/springbootjpa/customer/domain/Customer.java
- src/main/java/com/kdt/springbootjpa/item/domain/Car.java
- src/test/java/com/kdt/springbootjpa/customer/repository/CustomerRepositoryTest.java
> [2기 - P] 김산 :sparkles: Audit 적용

- src/main/java/com/dojinyou/devcourse/springbootjpa/common/entity/BaseEntity.java
- src/main/java/com/dojinyou/devcourse/springbootjpa/item/Car.java
- src/main/java/com/dojinyou/devcourse/springbootjpa/item/Food.java
- src/main/java/com/dojinyou/devcourse/springbootjpa/item/Furniture.java
- src/main/java/com/dojinyou/devcourse/springbootjpa/item/Item.java
- src/main/java/com/dojinyou/devcourse/springbootjpa/member/Member.java
- src/main/java/com/dojinyou/devcourse/springbootjpa/order/Order.java
- src/main/java/com/dojinyou/devcourse/springbootjpa/order/OrderItem.java
- src/main/java/com/dojinyou/devcourse/springbootjpa/order/OrderStatus.java
JPA 관련 Mission3: 연관관계매핑입니다.
1. Member, Order, OrderItem, Item 연관 관계 매핑
> [2기-C]유도진-Mission3: 연관관계 매핑 실습

- .gitignore
- mvnw
- mvnw.cmd
- pom.xml
- src/main/java/com/programmers/jpa/SpringbootJpaMissionApplication.java
- src/main/java/com/programmers/jpa/domain/order/Item.java
- src/main/java/com/programmers/jpa/domain/order/Member.java
- src/main/java/com/programmers/jpa/domain/order/Order.java
- src/main/java/com/programmers/jpa/domain/order/OrderItem.java
- src/main/java/com/programmers/jpa/domain/order/OrderStatus.java
- src/main/resources/application.yml
- src/test/java/com/programmers/jpa/domain/order/OrderTest.java
order, order_item, item 의 연관관계 매핑을 실습
order, order_item, item 의 연관관계 매핑을 실습 후 주문 생성 테스트
> [2기-C] 정해민 Mission 3: 연관관계 매핑 

- .gitignore
- mvnw
- mvnw.cmd
- pom.xml
- src/main/java/com/programmers/jpa/CustomerRepository.java
- src/main/java/com/programmers/jpa/SpringbootJpaMissionApplication.java
- src/main/java/com/programmers/jpa/domain/Customer.java
- src/main/resources/application.yml
- src/test/java/com/programmers/jpa/CustomerRepositoryTest.java
Customer 엔티티 CRUD 
Customer 엔티티와 레포지토리 구현 후 CRUD 테스트
> [2기-C] 정해민 Mission1. JPA소개

- pom.xml
- src/main/java/com/prgrms/springJpa/domain/customer/Customer.java
- src/main/java/com/prgrms/springJpa/domain/customer/CustomerRepository.java
- src/main/java/com/prgrms/springJpa/domain/order/Item.java
- src/main/java/com/prgrms/springJpa/domain/order/Member.java
- src/main/java/com/prgrms/springJpa/domain/order/Order.java
- src/main/java/com/prgrms/springJpa/domain/order/OrderItem.java
- src/main/java/com/prgrms/springJpa/domain/order/OrderStatus.java
- src/main/resources/application.yaml
- src/test/java/com/prgrms/springJpa/domain/PersistenceContextTest.java
- src/test/java/com/prgrms/springJpa/domain/customer/CustomerRepositoryTest.java
- src/test/java/com/prgrms/springJpa/domain/customer/PersistenceContextTest.java
- src/test/java/com/prgrms/springJpa/domain/order/OrderMappingTest.java
연관관계 매핑 및 테스트 
- 이번에는 롬복을 getter만 사용하였습니다. 
- 매핑의 경우 메서드로만 처리했습니다.
- 전에 머지를 sqush로 했더니 전에것도 중복해서 나오네요. 전에건 무시하고 봐주시면 감사하겠습니다...
> [2기-P] 유민환 Mission 3: 연관관계 매핑

- src/main/java/com/study/springbootJpa/domain/Item.java
- src/main/java/com/study/springbootJpa/domain/Member.java
- src/main/java/com/study/springbootJpa/domain/Order.java
- src/main/java/com/study/springbootJpa/domain/OrderItem.java
- src/main/java/com/study/springbootJpa/domain/OrderStatus.java
- src/main/java/com/study/springbootJpa/repository/Customer.java
- src/main/java/com/study/springbootJpa/repository/CustomerRepository.java
- src/test/java/com/study/springbootJpa/OrderMappingTest.java
- src/test/java/com/study/springbootJpa/PersistenceContextTest.java
- src/test/java/com/study/springbootJpa/SpringbootJpaApplicationTests.java
- src/test/java/com/study/springbootJpa/repository/CustomerRepositoryTest.java
> [2기-P] 박혜빈 Mission 3: 연관관계 매핑

- src/main/java/com/kdt/lecture/common/BaseEntity.java
- src/main/java/com/kdt/lecture/config/DataSourceConfig.java
- src/main/java/com/kdt/lecture/customer/Customer.java
- src/main/java/com/kdt/lecture/customer/CustomerRepository.java
- src/main/java/com/kdt/lecture/order/Car.java
- src/main/java/com/kdt/lecture/order/Food.java
- src/main/java/com/kdt/lecture/order/Furniture.java
- src/main/java/com/kdt/lecture/order/Item.java
- src/main/java/com/kdt/lecture/order/Member.java
- src/main/java/com/kdt/lecture/order/Order.java
- src/main/java/com/kdt/lecture/order/OrderItem.java
- src/main/java/com/kdt/lecture/order/OrderStatus.java
- src/test/java/com/kdt/lecture/customer/CustomerRepositoryTest.java
- src/test/java/com/kdt/lecture/customer/PersistTest.java
- src/test/java/com/kdt/lecture/order/MappingTest.java
<h>
* Member > Order : OneToMany
* Order > Member : ManyToOne
* Order > OrderItem : OneToMany
* OrderItem > Order : ManyToOne
* OrderItem > Item : ManyToOne
* Item > OrderItem : OneToMany
> [2기-P] 김형욱 Mission 3: 연관관계 매핑 

- src/main/java/org/prgrms/kdt/domain/order/Item.java
- src/main/java/org/prgrms/kdt/domain/order/Member.java
- src/main/java/org/prgrms/kdt/domain/order/Order.java
- src/main/java/org/prgrms/kdt/domain/order/OrderItem.java
- src/main/java/org/prgrms/kdt/domain/order/OrderStatus.java
- src/main/resources/application.yml
- src/test/java/org/prgrms/kdt/domain/order/AssociationMappingTest.java
> [2기-P] 곽동운 Mission 3: 연관관계 매핑

- app/src/main/java/com/programmers/app/domain/BaseEntity.java
- app/src/main/java/com/programmers/app/domain/order/Order.java
- app/src/main/java/com/programmers/app/domain/order/OrderItem.java
- app/src/main/java/com/programmers/app/domain/order/OrderStatus.java
- app/src/main/java/com/programmers/app/domain/order/item/Car.java
- app/src/main/java/com/programmers/app/domain/order/item/Food.java
- app/src/main/java/com/programmers/app/domain/order/item/Furniture.java
- app/src/main/java/com/programmers/app/domain/order/item/Item.java
- app/src/main/java/com/programmers/app/domain/order/member/Member.java
- 양방향 연관관계 설정
- orders : `1` OneToMany [collection]
- order_item `n`, `n` ManyToOne 
- product '1' -> OneToMany [collection]
- 양방향 편의 메소드 작성
> [2기-P] 김병연 Mission 3: 연관관계매핑

- .gitignore
- mvnw
- mvnw.cmd
- pom.xml
- src/main/java/com/kdt/jpaproject/SpringbootJpaApplication.java
- src/main/java/com/kdt/jpaproject/config/DataSourceConfig.java
- src/main/java/com/kdt/jpaproject/domain/Customer.java
- src/main/java/com/kdt/jpaproject/domain/CustomerRepository.java
- src/main/resources/application.yaml
- src/test/java/com/kdt/jpaproject/JPATest.java
- src/test/java/com/kdt/jpaproject/SpringbootJpaApplicationTests.java
- JPA 프로젝트를 세팅해본다.
- 세팅한 프로젝트를 이용해서 단일 엔티티를 이용한 CRUD를 구현한다.
- 고객(Customer) 엔티티는 ID(PK), 이름, 성을 가진다.
- 고객엔티티를 이용한 CRUD를 구현한다.
> [3기-C 김영빈] Mission 1: JPA 소개

- .gitignore
- pom.xml
- src/main/java/com/example/springboot_jpa/SpringbootJpaApplication.java
- src/main/java/com/example/springboot_jpa/domain/Customer.java
- src/main/java/com/example/springboot_jpa/domain/CustomerRepository.java
- src/main/resources/application.yml
- src/test/java/com/example/springboot_jpa/SpringbootJpaApplicationTests.java
- src/test/java/com/example/springboot_jpa/domain/CustomerRepositoryTest.java
* CRUD 기능을 test code 에서 작성하였는데 테스트를 적절하게 잘 했는지 궁금합니다
> [3기-C 이동준] 미션 1 리뷰 부탁드립니다!

- .gitignore
- pom.xml
- src/main/java/com/kdt/lecture/JpaOrderSystem.java
- src/main/java/com/kdt/lecture/config/DataSourceConfig.java
- src/main/java/com/kdt/lecture/domain/BaseEntity.java
- src/main/java/com/kdt/lecture/domain/member/Member.java
- src/main/java/com/kdt/lecture/domain/member/MemberRepository.java
- src/main/java/com/kdt/lecture/domain/order/Item.java
- src/main/java/com/kdt/lecture/domain/order/Order.java
- src/main/java/com/kdt/lecture/domain/order/OrderItem.java
- src/main/java/com/kdt/lecture/domain/order/OrderRepository.java
- src/main/java/com/kdt/lecture/domain/order/OrderStatus.java
- src/main/resources/application.yml
- src/test/java/com/kdt/lecture/JpaOrderSystemTest.java
- src/test/java/com/kdt/lecture/domain/member/MemberRepositoryTest.java
안녕하세요 앨런님, 승훈님, 수린님!🥰 이번 pr도 잘 부탁드립니다!
- 연관관계 매핑 실습
- 연관관계 매핑 테스트만 작성하였습니다
- repository테스트를 진행할때 어떤걸 테스트해야하는지 잘 기준이 서질 않습니다 필수로 해야하는 테스트 항목이 있을까요 ?
> [3기-C 서예원]Mission 3: 연관관계 매핑
